version: '3.9'

networks:
  lee:
    external: true

services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    networks:
      - lee
    environment:
      POSTGRES_PASSWORD: sksrhd!@34
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    networks:
      - lee
    environment:
      PGADMIN_DEFAULT_EMAIL: lee@nanoit.kr
      PGADMIN_DEFAULT_PASSWORD: sksrhd!@34
